// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------

libmex_path=file('join',['.','lib/libutil.dll']);
link(libmex_path);
libmex_path=file('join',['.','libmex.dll']);
addinter(libmex_path,'libmex');
