// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------

libmex_path=file('join',['.','lib/libutil.so']);
link(libmex_path);
libmex_path=file('join',['.','libmex.so']);
addinter(libmex_path,'libmex');
