# Generated automatically from Makefile.in by configure.
SHELL = /bin/sh

SCIDIR=../../../../
SCIDIR1=..\..\..\..\

include ../../../../Makefile.incl

CFLAGS_I = $(CC_OPTIONS) 

#-DSTANDALONE -MMD

CFLAGS =${CFLAGS_I} -I../generic 

UNIX_OBJS = tclUnixFCmd.o tclUnixFile.o 	tclUnixInit.o

GENERIC_OBJS =  regexp.o tclCmdAZ.o \
	tclFCmd.o tclFileName.o  tclIOUtil.o tclPosixStr.o \
	tclUtil.o Tobedone.o tclEnv.o  tcl2interf.o 

OBJS = ${GENERIC_OBJS} ${UNIX_OBJS} 

all :: ${OBJS}

clean::
	rm -f *.a *.o libtcl* core errs *~ \#* TAGS *.E a.out errors tclsh tcltest lib.exp

distclean:: clean


GENERIC_DIR=../generic

# Object files used on all Unix systems:

panic.o: $(GENERIC_DIR)/panic.c
	@echo "compiling $(GENERIC_DIR)/panic.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/panic.c

regexp.o: $(GENERIC_DIR)/regexp.c
	@echo "compiling $(GENERIC_DIR)/regexp.c"
	$(CC) -c $(CFLAGS) $(GENERIC_DIR)/regexp.c

tclAppInit.o: tclAppInit.c
	@echo "compiling tclAppInit.c"
	@$(CC) -c $(CFLAGS) tclAppInit.c

tclAsync.o: $(GENERIC_DIR)/tclAsync.c
	@echo "compiling $(GENERIC_DIR)/tclAsync.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclAsync.c

tclBasic.o: $(GENERIC_DIR)/tclBasic.c
	@echo "compiling $(GENERIC_DIR)/tclBasic.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclBasic.c

tclBinary.o: $(GENERIC_DIR)/tclBinary.c
	@echo "compiling $(GENERIC_DIR)/tclBinary.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclBinary.c

tclCkalloc.o: $(GENERIC_DIR)/tclCkalloc.c
	@echo "compiling $(GENERIC_DIR)/tclCkalloc.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclCkalloc.c

tclClock.o: $(GENERIC_DIR)/tclClock.c
	@echo "compiling $(GENERIC_DIR)/tclClock.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclClock.c

tclCmdAZ.o: $(GENERIC_DIR)/tclCmdAZ.c
	@echo "compiling $(GENERIC_DIR)/tclCmdAZ.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclCmdAZ.c

tclCmdIL.o: $(GENERIC_DIR)/tclCmdIL.c
	@echo "compiling $(GENERIC_DIR)/tclCmdIL.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclCmdIL.c

tclCmdMZ.o: $(GENERIC_DIR)/tclCmdMZ.c
	@echo "compiling $(GENERIC_DIR)/tclCmdMZ.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclCmdMZ.c

tclDate.o: $(GENERIC_DIR)/tclDate.c
	@echo "compiling $(GENERIC_DIR)/tclDate.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclDate.c

tclCompExpr.o: $(GENERIC_DIR)/tclCompExpr.c
	@echo "compiling $(GENERIC_DIR)/tclCompExpr.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclCompExpr.c

tclCompile.o: $(GENERIC_DIR)/tclCompile.c
	@echo "compiling $(GENERIC_DIR)/tclCompile.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclCompile.c

tclEnv.o: $(GENERIC_DIR)/tclEnv.c
	@echo "compiling $(GENERIC_DIR)/tclEnv.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclEnv.c

Tobedone.o: $(GENERIC_DIR)/Tobedone.c
	@echo "compiling $(GENERIC_DIR)/Tobedone.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/Tobedone.c

tcl2interf.o: $(GENERIC_DIR)/tcl2interf.c
	@echo "compiling $(GENERIC_DIR)/tcl2interf.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tcl2interf.c

tclEvent.o: $(GENERIC_DIR)/tclEvent.c
	@echo "compiling $(GENERIC_DIR)/tclEvent.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclEvent.c

tclExecute.o: $(GENERIC_DIR)/tclExecute.c
	@echo "compiling $(GENERIC_DIR)/tclExecute.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclExecute.c

tclFCmd.o: $(GENERIC_DIR)/tclFCmd.c
	@echo "compiling $(GENERIC_DIR)/tclFCmd.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclFCmd.c

tclFileName.o: $(GENERIC_DIR)/tclFileName.c
	@echo "compiling $(GENERIC_DIR)/tclFileName.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclFileName.c

tclGet.o: $(GENERIC_DIR)/tclGet.c
	@echo "compiling $(GENERIC_DIR)/tclGet.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclGet.c

tclHash.o: $(GENERIC_DIR)/tclHash.c
	@echo "compiling $(GENERIC_DIR)/tclHash.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclHash.c

tclHistory.o: $(GENERIC_DIR)/tclHistory.c
	@echo "compiling $(GENERIC_DIR)/tclHistory.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclHistory.c

tclIndexObj.o: $(GENERIC_DIR)/tclIndexObj.c
	@echo "compiling $(GENERIC_DIR)/tclIndexObj.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclIndexObj.c

tclInterp.o: $(GENERIC_DIR)/tclInterp.c
	@echo "compiling $(GENERIC_DIR)/tclInterp.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclInterp.c

tclIO.o: $(GENERIC_DIR)/tclIO.c
	@echo "compiling $(GENERIC_DIR)/tclIO.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclIO.c

tclIOCmd.o: $(GENERIC_DIR)/tclIOCmd.c
	@echo "compiling $(GENERIC_DIR)/tclIOCmd.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclIOCmd.c

tclIOSock.o: $(GENERIC_DIR)/tclIOSock.c
	@echo "compiling $(GENERIC_DIR)/tclIOSock.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclIOSock.c

tclIOUtil.o: $(GENERIC_DIR)/tclIOUtil.c
	@echo "compiling $(GENERIC_DIR)/tclIOUtil.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclIOUtil.c

tclLink.o: $(GENERIC_DIR)/tclLink.c
	@echo "compiling $(GENERIC_DIR)/tclLink.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclLink.c

tclListObj.o: $(GENERIC_DIR)/tclListObj.c
	@echo "compiling $(GENERIC_DIR)/tclListObj.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclListObj.c

tclObj.o: $(GENERIC_DIR)/tclObj.c
	@echo "compiling $(GENERIC_DIR)/tclObj.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclObj.c

tclMain.o: $(GENERIC_DIR)/tclMain.c
	@echo "compiling $(GENERIC_DIR)/tclMain.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclMain.c

tclNamesp.o: $(GENERIC_DIR)/tclNamesp.c
	@echo "compiling $(GENERIC_DIR)/tclNamesp.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclNamesp.c

tclNotify.o: $(GENERIC_DIR)/tclNotify.c
	@echo "compiling $(GENERIC_DIR)/tclNotify.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclNotify.c

tclParse.o: $(GENERIC_DIR)/tclParse.c
	@echo "compiling $(GENERIC_DIR)/tclParse.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclParse.c

tclPipe.o: $(GENERIC_DIR)/tclPipe.c
	@echo "compiling $(GENERIC_DIR)/tclPipe.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclPipe.c

tclPkg.o: $(GENERIC_DIR)/tclPkg.c
	@echo "compiling $(GENERIC_DIR)/tclPkg.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclPkg.c

tclPosixStr.o: $(GENERIC_DIR)/tclPosixStr.c
	@echo "compiling $(GENERIC_DIR)/tclPosixStr.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclPosixStr.c

tclPreserve.o: $(GENERIC_DIR)/tclPreserve.c
	@echo "compiling $(GENERIC_DIR)/tclPreserve.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclPreserve.c

tclProc.o: $(GENERIC_DIR)/tclProc.c
	@echo "compiling $(GENERIC_DIR)/tclProc.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclProc.c

tclStringObj.o: $(GENERIC_DIR)/tclStringObj.c
	@echo "compiling $(GENERIC_DIR)/tclStringObj.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclStringObj.c

tclUtil.o: $(GENERIC_DIR)/tclUtil.c
	@echo "compiling $(GENERIC_DIR)/tclUtil.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclUtil.c

tclVar.o: $(GENERIC_DIR)/tclVar.c
	@echo "compiling $(GENERIC_DIR)/tclVar.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclVar.c

tclTest.o: $(GENERIC_DIR)/tclTest.c
	@echo "compiling $(GENERIC_DIR)/tclTest.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclTest.c

tclTestObj.o: $(GENERIC_DIR)/tclTestObj.c
	@echo "compiling $(GENERIC_DIR)/tclTestObj.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclTestObj.c

tclTimer.o: $(GENERIC_DIR)/tclTimer.c
	@echo "compiling $(GENERIC_DIR)/tclTimer.c"
	@$(CC) -c $(CFLAGS) $(GENERIC_DIR)/tclTimer.c

tclUnixChan.o: tclUnixChan.c
	@echo "compiling tclUnixChan.c"
	@$(CC) -c $(CFLAGS) tclUnixChan.c

tclUnixEvent.o: tclUnixEvent.c
	@echo "compiling tclUnixEvent.c"
	@$(CC) -c $(CFLAGS) tclUnixEvent.c

tclUnixFCmd.o: tclUnixFCmd.c
	@echo "compiling tclUnixFCmd.c"
	@$(CC) -c $(CFLAGS) tclUnixFCmd.c

tclUnixFile.o: tclUnixFile.c
	@echo "compiling tclUnixFile.c"
	@$(CC) -c $(CFLAGS) tclUnixFile.c

tclUnixNotfy.o: tclUnixNotfy.c
	@echo "compiling tclUnixNotfy.c"
	@$(CC) -c $(CFLAGS) tclUnixNotfy.c

tclUnixPipe.o: tclUnixPipe.c
	@echo "compiling tclUnixPipe.c"
	@$(CC) -c $(CFLAGS) tclUnixPipe.c

tclUnixSock.o: tclUnixSock.c
	@echo "compiling tclUnixSock.c"
	@$(CC) -c $(CFLAGS) tclUnixSock.c

tclUnixTest.o: tclUnixTest.c
	@echo "compiling tclUnixTest.c"
	@$(CC) -c $(CFLAGS) tclUnixTest.c

tclUnixTime.o: tclUnixTime.c
	@echo "compiling tclUnixTime.c"
	@$(CC) -c $(CFLAGS) tclUnixTime.c

tclUnixInit.o: tclUnixInit.c 
	@echo "compiling tclUnixInit.c"
	@$(CC) -c $(CFLAGS) tclUnixInit.c

# compat binaries

fixstrtod.o: $(COMPAT_DIR)/fixstrtod.c
	@echo "compiling $(COMPAT_DIR)/fixstrtod.c"
	@$(CC) -c $(CFLAGS) $(COMPAT_DIR)/fixstrtod.c

getcwd.o: $(COMPAT_DIR)/getcwd.c
	@echo "compiling $(COMPAT_DIR)/getcwd.c"
	@$(CC) -c $(CFLAGS) $(COMPAT_DIR)/getcwd.c

opendir.o: $(COMPAT_DIR)/opendir.c
	@echo "compiling $(COMPAT_DIR)/opendir.c"
	@$(CC) -c $(CFLAGS) $(COMPAT_DIR)/opendir.c

strncasecmp.o: $(COMPAT_DIR)/strncasecmp.c
	@echo "compiling $(COMPAT_DIR)/strncasecmp.c"
	@$(CC) -c $(CFLAGS) $(COMPAT_DIR)/strncasecmp.c

strstr.o: $(COMPAT_DIR)/strstr.c
	@echo "compiling $(COMPAT_DIR)/strstr.c"
	@$(CC) -c $(CFLAGS) $(COMPAT_DIR)/strstr.c

strtod.o: $(COMPAT_DIR)/strtod.c
	@echo "compiling $(COMPAT_DIR)/strtod.c"
	@$(CC) -c $(CFLAGS) $(COMPAT_DIR)/strtod.c

strtol.o: $(COMPAT_DIR)/strtol.c
	@echo "compiling $(COMPAT_DIR)/strtol.c"
	@$(CC) -c $(CFLAGS) $(COMPAT_DIR)/strtol.c

strtoul.o: $(COMPAT_DIR)/strtoul.c
	@echo "compiling $(COMPAT_DIR)/strtoul.c"
	@$(CC) -c $(CFLAGS) $(COMPAT_DIR)/strtoul.c

tmpnam.o: $(COMPAT_DIR)/tmpnam.c
	@echo "compiling $(COMPAT_DIR)/tmpnam.c"
	@$(CC) -c $(CFLAGS) $(COMPAT_DIR)/tmpnam.c

waitpid.o: $(COMPAT_DIR)/waitpid.c
	@echo "compiling $(COMPAT_DIR)/waitpid.c"
	@$(CC) -c $(CFLAGS) $(COMPAT_DIR)/waitpid.c




