SHELL = /bin/sh

SCIDIR=../../

SUBDIRS= addinter-basic  addinter-general \
	 addinter-multi  addinter-tour  addinter-tutorial

all::
	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
	for i in $(SUBDIRS) ;\
	do \
		(cd $$i ; echo "making all in $$i..."; \
		$(MAKE) $(MFLAGS)  all ); \
	done

distclean::
	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
	for i in $(SUBDIRS) ;\
	do \
		(cd $$i ; echo "making distclean in $$i..."; \
		$(MAKE) $(MFLAGS)  distclean); \
	done

clean::
	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
	for i in $(SUBDIRS) ;\
	do \
		(cd $$i ; echo "making clean in $$i..."; \
		$(MAKE) $(MFLAGS) clean); \
	done

tests::
	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
	for i in $(SUBDIRS) ;\
	do \
		(cd $$i ; echo "making tests in $$i..."; \
		$(MAKE) $(MFLAGS)  tests); \
	done

