SHELL = /bin/sh

SCIDIR=../..
SCIDIR1=..\..

LIBRARY = nsp.a

# gobject.o

OBJSC = gtk.o gdk.o gboxed.o gobject.o  gdkatom.o  atk.o \
	pango.o pangoattribute.o to_be_done.o \
	to_be_done1.o gpointer.o strings.o \
	gmarkup.o gdate.o gdatetime.o \
	girepository-1.o gvalue.o webkit.o

OBJSF =

include ../../Makefile.incl
SCIDIR=../..

CFLAGS = $(CC_OPTIONS)

include ../Make.lib
