// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
libmulti_path="./" // get_file_path('loader.sce');
link(libmulti_path+'/lib/libutil.so');
ilib=link(libmulti_path+'/libmulti.so');
addinter(ilib,'libmulti1');
addinter(ilib,'libmulti2');
