// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------

libmulti_path=file('join',['.','lib/libutil.dll']);
link(libmulti_path);
libmulti_path=file('join',['.','libmulti.dll']);
ilib=link(libmulti_path);
addinter(ilib,'libmulti1');
addinter(ilib,'libmulti2');
