// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------

libmulti_path=file('join',['.','lib/libutil.so']);
link(libmulti_path);
libmulti_path=file('join',['.','libmulti.so']);
ilib=link(libmulti_path);
addinter(ilib,'libmulti1');
addinter(ilib,'libmulti2');
