#ifndef SCI_LAPACK_
#define SCI_LAPACK_


typedef long int logical;
typedef logical (*L_fp) (); /* A revoir au cas par cas XXXX */ 

typedef float E_f ;

extern int C2F(dbdsqr) _PARAMS((char *uplo, int *n, int *ncvt, int *nru, int *ncc, double *d__, double *e, double *vt, int *ldvt, double *u, int *ldu, double *c__, int *ldc, double *work, int *info, int uplo_len));
extern int C2F(dgebak) _PARAMS((char *job, char *side, int *n, int *ilo, int *ihi, double *scale, int *m, double *v, int *ldv, int *info, int job_len, int side_len));
extern int C2F(dgebal) _PARAMS((char *job, int *n, double *a, int *lda, int *ilo, int *ihi, double *scale, int *info, int job_len));
extern int C2F(dgebd2) _PARAMS((int *m, int *n, double *a, int *lda, double *d__, double *e, double *tauq, double *taup, double *work, int *info));
extern int C2F(dgebrd) _PARAMS((int *m, int *n, double *a, int *lda, double *d__, double *e, double *tauq, double *taup, double *work, int *lwork, int *info));
extern int C2F(dgecon) _PARAMS((char *norm, int *n, double *a, int *lda, double *anorm, double *rcond, double *work, int *iwork, int *info, int norm_len));
extern int C2F(dgeequ) _PARAMS((int *m, int *n, double *a, int *lda, double *r__, double *c__, double *rowcnd, double *colcnd, double *amax, int *info));
extern int C2F(dgees) _PARAMS((char *jobvs, char *sort, int (*select)(double *,double *), int *n, double *a, int *lda, int *sdim, double *wr, double *wi, double *vs, int *ldvs, double *work, int *lwork, int *bwork, int *info, int jobvs_len, int sort_len));
extern int C2F(dgeesx) _PARAMS((char *jobvs, char *sort, L_fp select, char *sense, int *n, double *a, int *lda, int *sdim, double *wr, double *wi, double *vs, int *ldvs, double *rconde, double *rcondv, double *work, int *lwork, int *iwork, int *liwork, int *bwork, int *info, int jobvs_len, int sort_len, int sense_len));
extern int C2F(dgeev) _PARAMS((char *jobvl, char *jobvr, int *n, double *a, int *lda, double *wr, double *wi, double *vl, int *ldvl, double *vr, int *ldvr, double *work, int *lwork, int *info, int jobvl_len, int jobvr_len));
extern int C2F(dgegs) _PARAMS((char *jobvsl, char *jobvsr, int *n, double *a, int *lda, double *b, int *ldb, double *alphar, double *alphai, double *beta, double *vsl, int *ldvsl, double *vsr, int *ldvsr, double *work, int *lwork, int *info, int jobvsl_len, int jobvsr_len));
extern int C2F(dgehd2) _PARAMS((int *n, int *ilo, int *ihi, double *a, int *lda, double *tau, double *work, int *info));
extern int C2F(dgehrd) _PARAMS((int *n, int *ilo, int *ihi, double *a, int *lda, double *tau, double *work, int *lwork, int *info));
extern int C2F(dgelq2) _PARAMS((int *m, int *n, double *a, int *lda, double *tau, double *work, int *info));
extern int C2F(dgelqf) _PARAMS((int *m, int *n, double *a, int *lda, double *tau, double *work, int *lwork, int *info));
extern int C2F(dgels) _PARAMS((char *trans, int *m, int *n, int *nrhs, double *a, int *lda, double *b, int *ldb, double *work, int *lwork, int *info, int trans_len));
extern int C2F(dgelss) _PARAMS((int *m, int *n, int *nrhs, double *a, int *lda, double *b, int *ldb, double *s, double *rcond, int *rank, double *work, int *lwork, int *info));
extern int C2F(dgelsx) _PARAMS((int *m, int *n, int *nrhs, double *a, int *lda, double *b, int *ldb, int *jpvt, double *rcond, int *rank, double *work, int *info));
extern int C2F(dgelsy) _PARAMS((int *m, int *n, int *nrhs, double *a, int *lda, double *b, int *ldb, int *jpvt, double *rcond, int *rank, double *work, int *lwork, int *info));
extern int C2F(dgeqlf) _PARAMS((int *m, int *n, double *a, int *lda, double *tau, double *work, int *lwork, int *info));
extern int C2F(dgeql2) _PARAMS((int *m, int *n, double *a, int *lda, double *tau, double *work, int *info));
extern int C2F(dgeqp3) _PARAMS((int *m, int *n, double *a, int *lda, int *jpvt, double *tau, double *work, int *lwork, int *info));
extern int C2F(dgeqpf) _PARAMS((int *m, int *n, double *a, int *lda, int *jpvt, double *tau, double *work, int *info));
extern int C2F(dgeqr2) _PARAMS((int *m, int *n, double *a, int *lda, double *tau, double *work, int *info));
extern int C2F(dgeqrf) _PARAMS((int *m, int *n, double *a, int *lda, double *tau, double *work, int *lwork, int *info));
extern int C2F(dgerfs) _PARAMS((char *trans, int *n, int *nrhs, double *a, int *lda, double *af, int *ldaf, int *ipiv, double *b, int *ldb, double *x, int *ldx, double *ferr, double *berr, double *work, int *iwork, int *info, int trans_len));
extern int C2F(dgerq2) _PARAMS((int *m, int *n, double *a, int *lda, double *tau, double *work, int *info));
extern int C2F(dgerqf) _PARAMS((int *m, int *n, double *a, int *lda, double *tau, double *work, int *lwork, int *info));
extern int C2F(dgesvd) _PARAMS((char *jobu, char *jobvt, int *m, int *n, double *a, int *lda, double *s, double *u, int *ldu, double *vt, int *ldvt, double *work, int *lwork, int *info, int jobu_len, int jobvt_len));
extern int C2F(dgesv) _PARAMS((int *n, int *nrhs, double *a, int *lda, int *ipiv, double *b, int *ldb, int *info));
extern int C2F(dgesvx) _PARAMS((char *fact, char *trans, int *n, int *nrhs, double *a, int *lda, double *af, int *ldaf, int *ipiv, char *equed, double *r__, double *c__, double *b, int *ldb, double *x, int *ldx, double *rcond, double *ferr, double *berr, double *work, int *iwork, int *info, int fact_len, int trans_len, int equed_len));
extern int C2F(dgetf2) _PARAMS((int *m, int *n, double *a, int *lda, int *ipiv, int *info));
extern int C2F(dgetrf) _PARAMS((int *m, int *n, double *a, int *lda, int *ipiv, int *info));
extern int C2F(dgetri) _PARAMS((int *n, double *a, int *lda, int *ipiv, double *work, int *lwork, int *info));
extern int C2F(dgetrs) _PARAMS((char *trans, int *n, int *nrhs, double *a, int *lda, int *ipiv, double *b, int *ldb, int *info, int trans_len));
extern int C2F(dggbak) _PARAMS((char *job, char *side, int *n, int *ilo, int *ihi, double *lscale, double *rscale, int *m, double *v, int *ldv, int *info, int job_len, int side_len));
extern int C2F(dggbal) _PARAMS((char *job, int *n, double *a, int *lda, double *b, int *ldb, int *ilo, int *ihi, double *lscale, double *rscale, double *work, int *info, int job_len));
extern int C2F(dgges) _PARAMS((char *jobvsl, char *jobvsr, char *sort, 
			       int (*F)(double *alphar,double *alphai,double *beta),
			       int *n, double *a, int *lda, double *b, int *ldb, int *sdim, double *alphar, double *alphai, double *beta, double *vsl, int *ldvsl, double *vsr, int *ldvsr, double *work, int *lwork, int *bwork, int *info, int jobvsl_len, int jobvsr_len, int sort_len));
extern int C2F(dlags2) _PARAMS((int *upper, double *a1, double *a2, double *a3, double *b1, double *b2, double *b3, double *csu, double *snu, double *csv, double *snv, double *csq, double *snq));
extern int C2F(dlagv2) _PARAMS((double *a, int *lda, double *b, int *ldb, double *alphar, double *alphai, double *beta, double *csl, double *snl, double *csr, double *snr));
extern int C2F(dlatdf) _PARAMS((int *ijob, int *n, double *z__, int *ldz, double *rhs, double *rdsum, double *rdscal, int *ipiv, int *jpiv));
extern int C2F(dtgex2) _PARAMS((int *wantq, int *wantz, int *n, double *a, int *lda, double *b, int *ldb, double *q, int *ldq, double *z__, int *ldz, int *j1, int *n1, int *n2, double *work, int *lwork, int *info));
extern int C2F(dtgexc) _PARAMS((int *wantq, int *wantz, int *n, double *a, int *lda, double *b, int *ldb, double *q, int *ldq, double *z__, int *ldz, int *ifst, int *ilst, double *work, int *lwork, int *info));
extern int C2F(dtgsy2) _PARAMS((char *trans, int *ijob, int *m, int *n, double *a, int *lda, double *b, int *ldb, double *c__, int *ldc, double *d__, int *ldd, double *e, int *lde, double *f, int *ldf, double *scale, double *rdsum, double *rdscal, int *iwork, int *pq, int *info, int trans_len));
extern int C2F(dtgsyl) _PARAMS((char *trans, int *ijob, int *m, int *n, double *a, int *lda, double *b, int *ldb, double *c__, int *ldc, double *d__, int *ldd, double *e, int *lde, double *f, int *ldf, double *scale, double *dif, double *work, int *lwork, int *iwork, int *info, int trans_len));
extern int C2F(dgesc2) _PARAMS((int *n, double *a, int *lda, double *rhs, int *ipiv, int *jpiv, double *scale));
extern int C2F(dgetc2) _PARAMS((int *n, double *a, int *lda, int *ipiv, int *jpiv, int *info));
extern int C2F(dtgsen) _PARAMS((int *ijob, int *wantq, int *wantz, int *select, int *n, double *a, int *lda, double *b, int *ldb, double *alphar, double *alphai, double *beta, double *q, int *ldq, double *z__, int *ldz, int *m, double *pl, double *pr, double *dif, double *work, int *lwork, int *iwork, int *liwork, int *info));
extern int C2F(dggev) _PARAMS((char *jobvl, char *jobvr, int *n, double *a, int *lda, double *b, int *ldb, double *alphar, double *alphai, double *beta, double *vl, int *ldvl, double *vr, int *ldvr, double *work, int *lwork, int *info, int jobvl_len, int jobvr_len));
extern int C2F(dgghrd) _PARAMS((char *compq, char *compz, int *n, int *ilo, int *ihi, double *a, int *lda, double *b, int *ldb, double *q, int *ldq, double *z__, int *ldz, int *info, int compq_len, int compz_len));
extern int C2F(dhgeqz) _PARAMS((char *job, char *compq, char *compz, int *n, int *ilo, int *ihi, double *a, int *lda, double *b, int *ldb, double *alphar, double *alphai, double *beta, double *q, int *ldq, double *z__, int *ldz, double *work, int *lwork, int *info, int job_len, int compq_len, int compz_len));
extern int C2F(dhseqr) _PARAMS((char *job, char *compz, int *n, int *ilo, int *ihi, double *h__, int *ldh, double *wr, double *wi, double *z__, int *ldz, double *work, int *lwork, int *info, int job_len, int compz_len));
extern int C2F(dlabad) _PARAMS((double *small, double *large));
extern int C2F(dlabrd) _PARAMS((int *m, int *n, int *nb, double *a, int *lda, double *d__, double *e, double *tauq, double *taup, double *x, int *ldx, double *y, int *ldy));
extern int C2F(dlacon) _PARAMS((int *n, double *v, double *x, int *isgn, double *est, int *kase));
extern int C2F(dlacpy) _PARAMS((char *uplo, int *m, int *n, double *a, int *lda, double *b, int *ldb, int uplo_len));
extern int C2F(dladiv) _PARAMS((double *a, double *b, double *c__, double *d__, double *p, double *q));
extern int C2F(dlae2) _PARAMS((double *a, double *b, double *c__, double *rt1, double *rt2));
extern int C2F(dlaev2) _PARAMS((double *a, double *b, double *c__, double *rt1, double *rt2, double *cs1, double *sn1));
extern int C2F(dlaexc) _PARAMS((int *wantq, int *n, double *t, int *ldt, double *q, int *ldq, int *j1, int *n1, int *n2, double *work, int *info));
extern int C2F(dlag2) _PARAMS((double *a, int *lda, double *b, int *ldb, double *safmin, double *scale1, double *scale2, double *wr1, double *wr2, double *wi));
extern int C2F(dlahqr) _PARAMS((int *wantt, int *wantz, int *n, int *ilo, int *ihi, double *h__, int *ldh, double *wr, double *wi, int *iloz, int *ihiz, double *z__, int *ldz, int *info));
extern int C2F(dlahrd) _PARAMS((int *n, int *k, int *nb, double *a, int *lda, double *tau, double *t, int *ldt, double *y, int *ldy));
extern int C2F(dlaic1) _PARAMS((int *job, int *j, double *x, double *sest, double *w, double *gamma, double *sestpr, double *s, double *c__));
extern int C2F(dlaln2) _PARAMS((int *ltrans, int *na, int *nw, double *smin, double *ca, double *a, int *lda, double *d1, double *d2, double *b, int *ldb, double *wr, double *wi, double *x, int *ldx, double *scale, double *xnorm, int *info));
extern double C2F(dlamch) _PARAMS((char *cmach, int cmach_len));
extern int C2F(dlamc1) _PARAMS((int *beta, int *t, int *rnd, int *ieee1));
extern int C2F(dlamc2) _PARAMS((int *beta, int *t, int *rnd, double *eps, int *emin, double *rmin, int *emax, double *rmax));
extern double C2F(dlamc3) _PARAMS((double *a, double *b));
extern int C2F(dlamc4) _PARAMS((int *emin, double *start, int *base));
extern int C2F(dlamc5) _PARAMS((int *beta, int *p, int *emin, int *ieee, int *emax, double *rmax));
extern double C2F(dlange) _PARAMS((char *norm, int *m, int *n, double *a, int *lda, double *work, int norm_len));
extern double C2F(dlanhs) _PARAMS((char *norm, int *n, double *a, int *lda, double *work, int norm_len));
extern double C2F(dlansp) _PARAMS((char *norm, char *uplo, int *n, double *ap, double *work, int norm_len, int uplo_len));
extern double C2F(dlanst) _PARAMS((char *norm, int *n, double *d__, double *e, int norm_len));
extern double C2F(dlansy) _PARAMS((char *norm, char *uplo, int *n, double *a, int *lda, double *work, int norm_len, int uplo_len));
extern double C2F(dlantr) _PARAMS((char *norm, char *uplo, char *diag, int *m, int *n, double *a, int *lda, double *work, int norm_len, int uplo_len, int diag_len));
extern int C2F(dlanv2) _PARAMS((double *a, double *b, double *c__, double *d__, double *rt1r, double *rt1i, double *rt2r, double *rt2i, double *cs, double *sn));
extern int C2F(dlapmt) _PARAMS((int *forwrd, int *m, int *n, double *x, int *ldx, int *k));
extern double C2F(dlapy2) _PARAMS((double *x, double *y));
extern double C2F(dlapy3) _PARAMS((double *x, double *y, double *z__));
extern int C2F(dlaqge) _PARAMS((int *m, int *n, double *a, int *lda, double *r__, double *c__, double *rowcnd, double *colcnd, double *amax, char *equed, int equed_len));
extern int C2F(dlaqp2) _PARAMS((int *m, int *n, int *offset, double *a, int *lda, int *jpvt, double *tau, double *vn1, double *vn2, double *work));
extern int C2F(dlaqps) _PARAMS((int *m, int *n, int *offset, int *nb, int *kb, double *a, int *lda, int *jpvt, double *tau, double *vn1, double *vn2, double *auxv, double *f, int *ldf));
extern int C2F(dlarfb) _PARAMS((char *side, char *trans, char *direct, char *storev, int *m, int *n, int *k, double *v, int *ldv, double *t, int *ldt, double *c__, int *ldc, double *work, int *ldwork, int side_len, int trans_len, int direct_len, int storev_len));
extern int C2F(dlarf) _PARAMS((char *side, int *m, int *n, double *v, int *incv, double *tau, double *c__, int *ldc, double *work, int side_len));
extern int C2F(dlarfg) _PARAMS((int *n, double *alpha, double *x, int *incx, double *tau));
extern int C2F(dlarft) _PARAMS((char *direct, char *storev, int *n, int *k, double *v, int *ldv, double *tau, double *t, int *ldt, int direct_len, int storev_len));
extern int C2F(dlarfx) _PARAMS((char *side, int *m, int *n, double *v, double *tau, double *c__, int *ldc, double *work, int side_len));
extern int C2F(dlartg) _PARAMS((double *f, double *g, double *cs, double *sn, double *r__));
extern int C2F(dlarzb) _PARAMS((char *side, char *trans, char *direct, char *storev, int *m, int *n, int *k, int *l, double *v, int *ldv, double *t, int *ldt, double *c__, int *ldc, double *work, int *ldwork, int side_len, int trans_len, int direct_len, int storev_len));
extern int C2F(dlarz) _PARAMS((char *side, int *m, int *n, int *l, double *v, int *incv, double *tau, double *c__, int *ldc, double *work, int side_len));
extern int C2F(dlarzt) _PARAMS((char *direct, char *storev, int *n, int *k, double *v, int *ldv, double *tau, double *t, int *ldt, int direct_len, int storev_len));
extern int C2F(dlas2) _PARAMS((double *f, double *g, double *h__, double *ssmin, double *ssmax));
extern int C2F(dlascl) _PARAMS((char *type__, int *kl, int *ku, double *cfrom, double *cto, int *m, int *n, double *a, int *lda, int *info, int type_len));
extern int C2F(dlaset) _PARAMS((char *uplo, int *m, int *n, double *alpha, double *beta, double *a, int *lda, int uplo_len));
extern int C2F(dlasq1) _PARAMS((int *n, double *d__, double *e, double *work, int *info));
extern int C2F(dlasq2) _PARAMS((int *m, double *q, double *e, double *qq, double *ee, double *eps, double *tol2, double *small2, double *sup, int *kend, int *info));
extern int C2F(dlasq3) _PARAMS((int *n, double *q, double *e, double *qq, double *ee, double *sup, double *sigma, int *kend, int *off, int *iphase, int *iconv, double *eps, double *tol2, double *small2));
extern int C2F(dlasq4) _PARAMS((int *n, double *q, double *e, double *tau, double *sup));
extern int C2F(dlasr) _PARAMS((char *side, char *pivot, char *direct, int *m, int *n, double *c__, double *s, double *a, int *lda, int side_len, int pivot_len, int direct_len));
extern int C2F(dlasrt) _PARAMS((char *id, int *n, double *d__, int *info, int id_len));
extern int C2F(dlassq) _PARAMS((int *n, double *x, int *incx, double *scale, double *sumsq));
extern int C2F(dlasv2) _PARAMS((double *f, double *g, double *h__, double *ssmin, double *ssmax, double *snr, double *csr, double *snl, double *csl));
extern int C2F(dlaswp) _PARAMS((int *n, double *a, int *lda, int *k1, int *k2, int *ipiv, int *incx));
extern int C2F(dlasy2) _PARAMS((int *ltranl, int *ltranr, int *isgn, int *n1, int *n2, double *tl, int *ldtl, double *tr, int *ldtr, double *b, int *ldb, double *scale, double *x, int *ldx, double *xnorm, int *info));
extern int C2F(dlasyf) _PARAMS((char *uplo, int *n, int *nb, int *kb, double *a, int *lda, int *ipiv, double *w, int *ldw, int *info, int uplo_len));
extern int C2F(dlatrs) _PARAMS((char *uplo, char *trans, char *diag, char *normin, int *n, double *a, int *lda, double *x, double *scale, double *cnorm, int *info, int uplo_len, int trans_len, int diag_len, int normin_len));
extern int C2F(dlatrz) _PARAMS((int *m, int *n, int *l, double *a, int *lda, double *tau, double *work));
extern int C2F(dlatzm) _PARAMS((char *side, int *m, int *n, double *v, int *incv, double *tau, double *c1, double *c2, int *ldc, double *work, int side_len));
extern int C2F(dopgtr) _PARAMS((char *uplo, int *n, double *ap, double *tau, double *q, int *ldq, double *work, int *info, int uplo_len));
extern int C2F(dorg2l) _PARAMS((int *m, int *n, int *k, double *a, int *lda, double *tau, double *work, int *info));
extern int C2F(dorg2r) _PARAMS((int *m, int *n, int *k, double *a, int *lda, double *tau, double *work, int *info));
extern int C2F(dorgbr) _PARAMS((char *vect, int *m, int *n, int *k, double *a, int *lda, double *tau, double *work, int *lwork, int *info, int vect_len));
extern int C2F(dorghr) _PARAMS((int *n, int *ilo, int *ihi, double *a, int *lda, double *tau, double *work, int *lwork, int *info));
extern int C2F(dorgl2) _PARAMS((int *m, int *n, int *k, double *a, int *lda, double *tau, double *work, int *info));
extern int C2F(dorglq) _PARAMS((int *m, int *n, int *k, double *a, int *lda, double *tau, double *work, int *lwork, int *info));
extern int C2F(dorgql) _PARAMS((int *m, int *n, int *k, double *a, int *lda, double *tau, double *work, int *lwork, int *info));
extern int C2F(dorgqr) _PARAMS((int *m, int *n, int *k, double *a, int *lda, double *tau, double *work, int *lwork, int *info));
extern int C2F(dorgr2) _PARAMS((int *m, int *n, int *k, double *a, int *lda, double *tau, double *work, int *info));
extern int C2F(dorgrq) _PARAMS((int *m, int *n, int *k, double *a, int *lda, double *tau, double *work, int *lwork, int *info));
extern int C2F(dorgtr) _PARAMS((char *uplo, int *n, double *a, int *lda, double *tau, double *work, int *lwork, int *info, int uplo_len));
extern int C2F(dorm2r) _PARAMS((char *side, char *trans, int *m, int *n, int *k, double *a, int *lda, double *tau, double *c__, int *ldc, double *work, int *info, int side_len, int trans_len));
extern int C2F(dormbr) _PARAMS((char *vect, char *side, char *trans, int *m, int *n, int *k, double *a, int *lda, double *tau, double *c__, int *ldc, double *work, int *lwork, int *info, int vect_len, int side_len, int trans_len));
extern int C2F(dormhr) _PARAMS((char *side, char *trans, int *m, int *n, int *ilo, int *ihi, double *a, int *lda, double *tau, double *c__, int *ldc, double *work, int *lwork, int *info, int side_len, int trans_len));
extern int C2F(dorml2) _PARAMS((char *side, char *trans, int *m, int *n, int *k, double *a, int *lda, double *tau, double *c__, int *ldc, double *work, int *info, int side_len, int trans_len));
extern int C2F(dormlq) _PARAMS((char *side, char *trans, int *m, int *n, int *k, double *a, int *lda, double *tau, double *c__, int *ldc, double *work, int *lwork, int *info, int side_len, int trans_len));
extern int C2F(dormql) _PARAMS((char *side, char *trans, int *m, int *n, int *k, double *a, int *lda, double *tau, double *c__, int *ldc, double *work, int *lwork, int *info, int side_len, int trans_len));
extern int C2F(dorm2l) _PARAMS((char *side, char *trans, int *m, int *n, int *k, double *a, int *lda, double *tau, double *c__, int *ldc, double *work, int *info, int side_len, int trans_len));
extern int C2F(dormqr) _PARAMS((char *side, char *trans, int *m, int *n, int *k, double *a, int *lda, double *tau, double *c__, int *ldc, double *work, int *lwork, int *info, int side_len, int trans_len));
extern int C2F(dormr2) _PARAMS((char *side, char *trans, int *m, int *n, int *k, double *a, int *lda, double *tau, double *c__, int *ldc, double *work, int *info, int side_len, int trans_len));
extern int C2F(dormr3) _PARAMS((char *side, char *trans, int *m, int *n, int *k, int *l, double *a, int *lda, double *tau, double *c__, int *ldc, double *work, int *info, int side_len, int trans_len));
extern int C2F(dormrq) _PARAMS((char *side, char *trans, int *m, int *n, int *k, double *a, int *lda, double *tau, double *c__, int *ldc, double *work, int *lwork, int *info, int side_len, int trans_len));
extern int C2F(dormrz) _PARAMS((char *side, char *trans, int *m, int *n, int *k, int *l, double *a, int *lda, double *tau, double *c__, int *ldc, double *work, int *lwork, int *info, int side_len, int trans_len));
extern int C2F(dpocon) _PARAMS((char *uplo, int *n, double *a, int *lda, double *anorm, double *rcond, double *work, int *iwork, int *info, int uplo_len));
extern int C2F(dpotrf) _PARAMS((char *uplo, int *n, double *a, int *lda, int *info, int uplo_len));
extern int C2F(dpotf2) _PARAMS((char *uplo, int *n, double *a, int *lda, int *info, int uplo_len));
extern int C2F(dpotrs) _PARAMS((char *uplo, int *n, int *nrhs, double *a, int *lda, double *b, int *ldb, int *info, int uplo_len));
extern int C2F(dpptrf) _PARAMS((char *uplo, int *n, double *ap, int *info, int uplo_len));
extern int C2F(drscl) _PARAMS((int *n, double *sa, double *sx, int *incx));
extern int C2F(dspev) _PARAMS((char *jobz, char *uplo, int *n, double *ap, double *w, double *z__, int *ldz, double *work, int *info, int jobz_len, int uplo_len));
extern int C2F(dspgst) _PARAMS((int *itype, char *uplo, int *n, double *ap, double *bp, int *info, int uplo_len));
extern int C2F(dspgv) _PARAMS((int *itype, char *jobz, char *uplo, int *n, double *ap, double *bp, double *w, double *z__, int *ldz, double *work, int *info, int jobz_len, int uplo_len));
extern int C2F(dsptrd) _PARAMS((char *uplo, int *n, double *ap, double *d__, double *e, double *tau, int *info, int uplo_len));
extern int C2F(dsptrf) _PARAMS((char *uplo, int *n, double *ap, int *ipiv, int *info, int uplo_len));
extern int C2F(dsteqr) _PARAMS((char *compz, int *n, double *d__, double *e, double *z__, int *ldz, double *work, int *info, int compz_len));
extern int C2F(dsterf) _PARAMS((int *n, double *d__, double *e, int *info));
extern int C2F(dsycon) _PARAMS((char *uplo, int *n, double *a, int *lda, int *ipiv, double *anorm, double *rcond, double *work, int *iwork, int *info, int uplo_len));
extern int C2F(dsyev) _PARAMS((char *jobz, char *uplo, int *n, double *a, int *lda, double *w, double *work, int *lwork, int *info, int jobz_len, int uplo_len));
extern int C2F(dsysv) _PARAMS((char *uplo, int *n, int *nrhs, double *a, int *lda, int *ipiv, double *b, int *ldb, double *work, int *lwork, int *info, int uplo_len));
extern int C2F(dsytf2) _PARAMS((char *uplo, int *n, double *a, int *lda, int *ipiv, int *info, int uplo_len));
extern int C2F(dsytrd) _PARAMS((char *uplo, int *n, double *a, int *lda, double *d__, double *e, double *tau, double *work, int *lwork, int *info, int uplo_len));
extern int C2F(dlatrd) _PARAMS((char *uplo, int *n, int *nb, double *a, int *lda, double *e, double *tau, double *w, int *ldw, int uplo_len));
extern int C2F(dsytd2) _PARAMS((char *uplo, int *n, double *a, int *lda, double *d__, double *e, double *tau, int *info, int uplo_len));
extern int C2F(dsytrf) _PARAMS((char *uplo, int *n, double *a, int *lda, int *ipiv, double *work, int *lwork, int *info, int uplo_len));
extern int C2F(dsytri) _PARAMS((char *uplo, int *n, double *a, int *lda, int *ipiv, double *work, int *info, int uplo_len));
extern int C2F(dsytrs) _PARAMS((char *uplo, int *n, int *nrhs, double *a, int *lda, int *ipiv, double *b, int *ldb, int *info, int uplo_len));
extern int C2F(dtgevc) _PARAMS((char *side, char *howmny, int *select, int *n, double *a, int *lda, double *b, int *ldb, double *vl, int *ldvl, double *vr, int *ldvr, int *mm, int *m, double *work, int *info, int side_len, int howmny_len));
extern int C2F(dtrcon) _PARAMS((char *norm, char *uplo, char *diag, int *n, double *a, int *lda, double *rcond, double *work, int *iwork, int *info, int norm_len, int uplo_len, int diag_len));
extern int C2F(dtrevc) _PARAMS((char *side, char *howmny, int *select, int *n, double *t, int *ldt, double *vl, int *ldvl, double *vr, int *ldvr, int *mm, int *m, double *work, int *info, int side_len, int howmny_len));
extern int C2F(dtrexc) _PARAMS((char *compq, int *n, double *t, int *ldt, double *q, int *ldq, int *ifst, int *ilst, double *work, int *info, int compq_len));
extern int C2F(dtrsen) _PARAMS((char *job, char *compq, int *select, int *n, double *t, int *ldt, double *q, int *ldq, double *wr, double *wi, int *m, double *s, double *sep, double *work, int *lwork, int *iwork, int *liwork, int *info, int job_len, int compq_len));
extern int C2F(dtrsyl) _PARAMS((char *trana, char *tranb, int *isgn, int *m, int *n, double *a, int *lda, double *b, int *ldb, double *c__, int *ldc, double *scale, int *info, int trana_len, int tranb_len));
extern int C2F(dtrti2) _PARAMS((char *uplo, char *diag, int *n, double *a, int *lda, int *info, int uplo_len, int diag_len));
extern int C2F(dtrtri) _PARAMS((char *uplo, char *diag, int *n, double *a, int *lda, int *info, int uplo_len, int diag_len));
extern int C2F(dtrtrs) _PARAMS((char *uplo, char *trans, char *diag, int *n, int *nrhs, double *a, int *lda, double *b, int *ldb, int *info, int uplo_len, int trans_len, int diag_len));
extern int C2F(dtzrqf) _PARAMS((int *m, int *n, double *a, int *lda, double *tau, int *info));
extern int C2F(dtzrzf) _PARAMS((int *m, int *n, double *a, int *lda, double *tau, double *work, int *lwork, int *info));
extern double C2F(dzsum1) _PARAMS((int *n, doubleC *cx, int *incx));
extern int C2F(ilaenv) _PARAMS((int *ispec, char *name__, char *opts, int *n1, int *n2, int *n3, int *n4, int name_len, int opts_len));
extern int C2F(izmax1) _PARAMS((int *n, doubleC *cx, int *incx));
extern int C2F(lsame) _PARAMS((char *ca, char *cb, int ca_len, int cb_len));
extern E_f  C2F(slamch) _PARAMS((char *cmach, int cmach_len));
extern int C2F(slamc1) _PARAMS((int *beta, int *t, int *rnd, int *ieee1));
extern int C2F(slamc2) _PARAMS((int *beta, int *t, int *rnd, float *eps, int *emin, float *rmin, int *emax, float *rmax));
extern E_f C2F(slamc3) _PARAMS((float *a, float *b));
extern int C2F(slamc4) _PARAMS((int *emin, float *start, int *base));
extern int C2F(slamc5) _PARAMS((int *beta, int *p, int *emin, int *ieee, int *emax, float *rmax));
extern int C2F(xerbla) _PARAMS((char *srname, int *info, int srname_len));
extern int C2F(zbdsqr) _PARAMS((char *uplo, int *n, int *ncvt, int *nru, int *ncc, double *d__, double *e, doubleC *vt, int *ldvt, doubleC *u, int *ldu, doubleC *c__, int *ldc, double *rwork, int *info, int uplo_len));
extern int C2F(zdrot) _PARAMS((int *n, doubleC *cx, int *incx, doubleC *cy, int *incy, double *c__, double *s));
extern int C2F(zdrscl) _PARAMS((int *n, double *sa, doubleC *sx, int *incx));
extern int C2F(zgebak) _PARAMS((char *job, char *side, int *n, int *ilo, int *ihi, double *scale, int *m, doubleC *v, int *ldv, int *info, int job_len, int side_len));
extern int C2F(zgebal) _PARAMS((char *job, int *n, doubleC *a, int *lda, int *ilo, int *ihi, double *scale, int *info, int job_len));
extern int C2F(zgebd2) _PARAMS((int *m, int *n, doubleC *a, int *lda, double *d__, double *e, doubleC *tauq, doubleC *taup, doubleC *work, int *info));
extern int C2F(zgebrd) _PARAMS((int *m, int *n, doubleC *a, int *lda, double *d__, double *e, doubleC *tauq, doubleC *taup, doubleC *work, int *lwork, int *info));
extern int C2F(zgecon) _PARAMS((char *norm, int *n, doubleC *a, int *lda, double *anorm, double *rcond, doubleC *work, double *rwork, int *info, int norm_len));
extern int C2F(zgees) _PARAMS((char *jobvs, char *sort,int (*select)(doubleC *), int *n, doubleC *a, int *lda, int *sdim, doubleC *w, doubleC *vs, int *ldvs, doubleC *work, int *lwork, double *rwork, int *bwork, int *info, int jobvs_len, int sort_len));
extern int C2F(zgeev) _PARAMS((char *jobvl, char *jobvr, int *n, doubleC *a, int *lda, doubleC *w, doubleC *vl, int *ldvl, doubleC *vr, int *ldvr, doubleC *work, int *lwork, double *rwork, int *info, int jobvl_len, int jobvr_len));
extern int C2F(zgehd2) _PARAMS((int *n, int *ilo, int *ihi, doubleC *a, int *lda, doubleC *tau, doubleC *work, int *info));
extern int C2F(zgehrd) _PARAMS((int *n, int *ilo, int *ihi, doubleC *a, int *lda, doubleC *tau, doubleC *work, int *lwork, int *info));
extern int C2F(zgelq2) _PARAMS((int *m, int *n, doubleC *a, int *lda, doubleC *tau, doubleC *work, int *info));
extern int C2F(zgelqf) _PARAMS((int *m, int *n, doubleC *a, int *lda, doubleC *tau, doubleC *work, int *lwork, int *info));
extern int C2F(zgelsy) _PARAMS((int *m, int *n, int *nrhs, doubleC *a, int *lda, doubleC *b, int *ldb, int *jpvt, double *rcond, int *rank, doubleC *work, int *lwork, double *rwork, int *info));
extern int C2F(zgeqp3) _PARAMS((int *m, int *n, doubleC *a, int *lda, int *jpvt, doubleC *tau, doubleC *work, int *lwork, double *rwork, int *info));
extern int C2F(zgeqpf) _PARAMS((int *m, int *n, doubleC *a, int *lda, int *jpvt, doubleC *tau, doubleC *work, double *rwork, int *info));
extern int C2F(zgeqr2) _PARAMS((int *m, int *n, doubleC *a, int *lda, doubleC *tau, doubleC *work, int *info));
extern int C2F(zgeqrf) _PARAMS((int *m, int *n, doubleC *a, int *lda, doubleC *tau, doubleC *work, int *lwork, int *info));
extern int C2F(zgesc2) _PARAMS((int *n, doubleC *a, int *lda, doubleC *rhs, int *ipiv, int *jpiv, double *scale));
extern int C2F(zgesvd) _PARAMS((char *jobu, char *jobvt, int *m, int *n, doubleC *a, int *lda, double *s, doubleC *u, int *ldu, doubleC *vt, int *ldvt, doubleC *work, int *lwork, double *rwork, int *info, int jobu_len, int jobvt_len));
extern int C2F(zgetc2) _PARAMS((int *n, doubleC *a, int *lda, int *ipiv, int *jpiv, int *info));
extern int C2F(zgetf2) _PARAMS((int *m, int *n, doubleC *a, int *lda, int *ipiv, int *info));
extern int C2F(zgetrf) _PARAMS((int *m, int *n, doubleC *a, int *lda, int *ipiv, int *info));
extern int C2F(zgetri) _PARAMS((int *n, doubleC *a, int *lda, int *ipiv, doubleC *work, int *lwork, int *info));
extern int C2F(zgetrs) _PARAMS((char *trans, int *n, int *nrhs, doubleC *a, int *lda, int *ipiv, doubleC *b, int *ldb, int *info, int trans_len));
extern int C2F(zggbak) _PARAMS((char *job, char *side, int *n, int *ilo, int *ihi, double *lscale, double *rscale, int *m, doubleC *v, int *ldv, int *info, int job_len, int side_len));
extern int C2F(zggbal) _PARAMS((char *job, int *n, doubleC *a, int *lda, doubleC *b, int *ldb, int *ilo, int *ihi, double *lscale, double *rscale, double *work, int *info, int job_len));
extern int C2F(zgges) _PARAMS((char *jobvsl, char *jobvsr, char *sort,
			       int (*F)(doubleC *alpha,doubleC *beta),
			       int *n, doubleC *a, int *lda, doubleC *b, int *ldb, int *sdim, doubleC *alpha, doubleC *beta, doubleC *vsl, int *ldvsl, doubleC *vsr, int *ldvsr, doubleC *work, int *lwork, double *rwork, int *bwork, int *info, int jobvsl_len, int jobvsr_len, int sort_len));
extern int C2F(zggev) _PARAMS((char *jobvl, char *jobvr, int *n, doubleC *a, int *lda, doubleC *b, int *ldb, doubleC *alpha, doubleC *beta, doubleC *vl, int *ldvl, doubleC *vr, int *ldvr, doubleC *work, int *lwork, double *rwork, int *info, int jobvl_len, int jobvr_len));
extern int C2F(zgghrd) _PARAMS((char *compq, char *compz, int *n, int *ilo, int *ihi, doubleC *a, int *lda, doubleC *b, int *ldb, doubleC *q, int *ldq, doubleC *z__, int *ldz, int *info, int compq_len, int compz_len));
extern int C2F(zheev) _PARAMS((char *jobz, char *uplo, int *n, doubleC *a, int *lda, double *w, doubleC *work, int *lwork, double *rwork, int *info, int jobz_len, int uplo_len));
extern int C2F(zhetd2) _PARAMS((char *uplo, int *n, doubleC *a, int *lda, double *d__, double *e, doubleC *tau, int *info, int uplo_len));
extern int C2F(zhetrd) _PARAMS((char *uplo, int *n, doubleC *a, int *lda, double *d__, double *e, doubleC *tau, doubleC *work, int *lwork, int *info, int uplo_len));
extern int C2F(zhgeqz) _PARAMS((char *job, char *compq, char *compz, int *n, int *ilo, int *ihi, doubleC *a, int *lda, doubleC *b, int *ldb, doubleC *alpha, doubleC *beta, doubleC *q, int *ldq, doubleC *z__, int *ldz, doubleC *work, int *lwork, double *rwork, int *info, int job_len, int compq_len, int compz_len));
extern int C2F(zhseqr) _PARAMS((char *job, char *compz, int *n, int *ilo, int *ihi, doubleC *h__, int *ldh, doubleC *w, doubleC *z__, int *ldz, doubleC *work, int *lwork, int *info, int job_len, int compz_len));
extern int C2F(zlabrd) _PARAMS((int *m, int *n, int *nb, doubleC *a, int *lda, double *d__, double *e, doubleC *tauq, doubleC *taup, doubleC *x, int *ldx, doubleC *y, int *ldy));
extern int C2F(zlacgv) _PARAMS((int *n, doubleC *x, int *incx));
extern int C2F(zlacon) _PARAMS((int *n, doubleC *v, doubleC *x, double *est, int *kase));
extern int C2F(zlacpy) _PARAMS((char *uplo, int *m, int *n, doubleC *a, int *lda, doubleC *b, int *ldb, int uplo_len));
extern void C2F(zladiv) _PARAMS((doubleC * ret_val, doubleC *x, doubleC *y));
extern int C2F(zlahqr) _PARAMS((int *wantt, int *wantz, int *n, int *ilo, int *ihi, doubleC *h__, int *ldh, doubleC *w, int *iloz, int *ihiz, doubleC *z__, int *ldz, int *info));
extern int C2F(zlahrd) _PARAMS((int *n, int *k, int *nb, doubleC *a, int *lda, doubleC *tau, doubleC *t, int *ldt, doubleC *y, int *ldy));
extern int C2F(zlaic1) _PARAMS((int *job, int *j, doubleC *x, double *sest, doubleC *w, doubleC *gamma, double *sestpr, doubleC *s, doubleC *c__));
extern double C2F(zlange) _PARAMS((char *norm, int *m, int *n, doubleC *a, int *lda, double *work, int norm_len));
extern double C2F(zlanhe) _PARAMS((char *norm, char *uplo, int *n, doubleC *a, int *lda, double *work, int norm_len, int uplo_len));
extern double C2F(zlanhs) _PARAMS((char *norm, int *n, doubleC *a, int *lda, double *work, int norm_len));
extern int C2F(zlaqp2) _PARAMS((int *m, int *n, int *offset, doubleC *a, int *lda, int *jpvt, doubleC *tau, double *vn1, double *vn2, doubleC *work));
extern int C2F(zlaqps) _PARAMS((int *m, int *n, int *offset, int *nb, int *kb, doubleC *a, int *lda, int *jpvt, doubleC *tau, double *vn1, double *vn2, doubleC *auxv, doubleC *f, int *ldf));
extern int C2F(zlarfb) _PARAMS((char *side, char *trans, char *direct, char *storev, int *m, int *n, int *k, doubleC *v, int *ldv, doubleC *t, int *ldt, doubleC *c__, int *ldc, doubleC *work, int *ldwork, int side_len, int trans_len, int direct_len, int storev_len));
extern int C2F(zlarf) _PARAMS((char *side, int *m, int *n, doubleC *v, int *incv, doubleC *tau, doubleC *c__, int *ldc, doubleC *work, int side_len));
extern int C2F(zlarfg) _PARAMS((int *n, doubleC *alpha, doubleC *x, int *incx, doubleC *tau));
extern int C2F(zlarft) _PARAMS((char *direct, char *storev, int *n, int *k, doubleC *v, int *ldv, doubleC *tau, doubleC *t, int *ldt, int direct_len, int storev_len));
extern int C2F(zlarfx) _PARAMS((char *side, int *m, int *n, doubleC *v, doubleC *tau, doubleC *c__, int *ldc, doubleC *work, int side_len));
extern int C2F(zlartg) _PARAMS((doubleC *f, doubleC *g, double *cs, doubleC *sn, doubleC *r__));
extern int C2F(zlarzb) _PARAMS((char *side, char *trans, char *direct, char *storev, int *m, int *n, int *k, int *l, doubleC *v, int *ldv, doubleC *t, int *ldt, doubleC *c__, int *ldc, doubleC *work, int *ldwork, int side_len, int trans_len, int direct_len, int storev_len));
extern int C2F(zlarz) _PARAMS((char *side, int *m, int *n, int *l, doubleC *v, int *incv, doubleC *tau, doubleC *c__, int *ldc, doubleC *work, int side_len));
extern int C2F(zlarzt) _PARAMS((char *direct, char *storev, int *n, int *k, doubleC *v, int *ldv, doubleC *tau, doubleC *t, int *ldt, int direct_len, int storev_len));
extern int C2F(zlascl) _PARAMS((char *type__, int *kl, int *ku, double *cfrom, double *cto, int *m, int *n, doubleC *a, int *lda, int *info, int type_len));
extern int C2F(zlaset) _PARAMS((char *uplo, int *m, int *n, doubleC *alpha, doubleC *beta, doubleC *a, int *lda, int uplo_len));
extern int C2F(zlasr) _PARAMS((char *side, char *pivot, char *direct, int *m, int *n, double *c__, double *s, doubleC *a, int *lda, int side_len, int pivot_len, int direct_len));
extern int C2F(zlassq) _PARAMS((int *n, doubleC *x, int *incx, double *scale, double *sumsq));
extern int C2F(zlaswp) _PARAMS((int *n, doubleC *a, int *lda, int *k1, int *k2, int *ipiv, int *incx));
extern int C2F(zlatdf) _PARAMS((int *ijob, int *n, doubleC *z__, int *ldz, doubleC *rhs, double *rdsum, double *rdscal, int *ipiv, int *jpiv));
extern int C2F(zlatrd) _PARAMS((char *uplo, int *n, int *nb, doubleC *a, int *lda, double *e, doubleC *tau, doubleC *w, int *ldw, int uplo_len));
extern int C2F(zlatrs) _PARAMS((char *uplo, char *trans, char *diag, char *normin, int *n, doubleC *a, int *lda, doubleC *x, double *scale, double *cnorm, int *info, int uplo_len, int trans_len, int diag_len, int normin_len));
extern int C2F(zlatrz) _PARAMS((int *m, int *n, int *l, doubleC *a, int *lda, doubleC *tau, doubleC *work));
extern int C2F(zpotf2) _PARAMS((char *uplo, int *n, doubleC *a, int *lda, int *info, int uplo_len));
extern int C2F(zpotrf) _PARAMS((char *uplo, int *n, doubleC *a, int *lda, int *info, int uplo_len));
extern int C2F(zrot) _PARAMS((int *n, doubleC *cx, int *incx, doubleC *cy, int *incy, double *c__, doubleC *s));
extern int C2F(zsteqr) _PARAMS((char *compz, int *n, double *d__, double *e, doubleC *z__, int *ldz, double *work, int *info, int compz_len));
extern int C2F(ztgevc) _PARAMS((char *side, char *howmny, int *select, int *n, doubleC *a, int *lda, doubleC *b, int *ldb, doubleC *vl, int *ldvl, doubleC *vr, int *ldvr, int *mm, int *m, doubleC *work, double *rwork, int *info, int side_len, int howmny_len));
extern int C2F(ztgex2) _PARAMS((int *wantq, int *wantz, int *n, doubleC *a, int *lda, doubleC *b, int *ldb, doubleC *q, int *ldq, doubleC *z__, int *ldz, int *j1, int *info));
extern int C2F(ztgexc) _PARAMS((int *wantq, int *wantz, int *n, doubleC *a, int *lda, doubleC *b, int *ldb, doubleC *q, int *ldq, doubleC *z__, int *ldz, int *ifst, int *ilst, int *info));
extern int C2F(ztgsen) _PARAMS((int *ijob, int *wantq, int *wantz, int *select, int *n, doubleC *a, int *lda, doubleC *b, int *ldb, doubleC *alpha, doubleC *beta, doubleC *q, int *ldq, doubleC *z__, int *ldz, int *m, double *pl, double *pr, double *dif, doubleC *work, int *lwork, int *iwork, int *liwork, int *info));
extern int C2F(ztgsy2) _PARAMS((char *trans, int *ijob, int *m, int *n, doubleC *a, int *lda, doubleC *b, int *ldb, doubleC *c__, int *ldc, doubleC *d__, int *ldd, doubleC *e, int *lde, doubleC *f, int *ldf, double *scale, double *rdsum, double *rdscal, int *info, int trans_len));
extern int C2F(ztgsyl) _PARAMS((char *trans, int *ijob, int *m, int *n, doubleC *a, int *lda, doubleC *b, int *ldb, doubleC *c__, int *ldc, doubleC *d__, int *ldd, doubleC *e, int *lde, doubleC *f, int *ldf, double *scale, double *dif, doubleC *work, int *lwork, int *iwork, int *info, int trans_len));
extern int C2F(ztrevc) _PARAMS((char *side, char *howmny, int *select, int *n, doubleC *t, int *ldt, doubleC *vl, int *ldvl, doubleC *vr, int *ldvr, int *mm, int *m, doubleC *work, double *rwork, int *info, int side_len, int howmny_len));
extern int C2F(ztrexc) _PARAMS((char *compq, int *n, doubleC *t, int *ldt, doubleC *q, int *ldq, int *ifst, int *ilst, int *info, int compq_len));
extern int C2F(ztrsen) _PARAMS((char *job, char *compq, int *select, int *n, doubleC *t, int *ldt, doubleC *q, int *ldq, doubleC *w, int *m, double *s, double *sep, doubleC *work, int *lwork, int *info, int job_len, int compq_len));
extern int C2F(ztrsyl) _PARAMS((char *trana, char *tranb, int *isgn, int *m, int *n, doubleC *a, int *lda, doubleC *b, int *ldb, doubleC *c__, int *ldc, double *scale, int *info, int trana_len, int tranb_len));
extern int C2F(ztrti2) _PARAMS((char *uplo, char *diag, int *n, doubleC *a, int *lda, int *info, int uplo_len, int diag_len));
extern int C2F(ztrtri) _PARAMS((char *uplo, char *diag, int *n, doubleC *a, int *lda, int *info, int uplo_len, int diag_len));
extern int C2F(ztzrzf) _PARAMS((int *m, int *n, doubleC *a, int *lda, doubleC *tau, doubleC *work, int *lwork, int *info));
extern int C2F(zung2l) _PARAMS((int *m, int *n, int *k, doubleC *a, int *lda, doubleC *tau, doubleC *work, int *info));
extern int C2F(zung2r) _PARAMS((int *m, int *n, int *k, doubleC *a, int *lda, doubleC *tau, doubleC *work, int *info));
extern int C2F(zungbr) _PARAMS((char *vect, int *m, int *n, int *k, doubleC *a, int *lda, doubleC *tau, doubleC *work, int *lwork, int *info, int vect_len));
extern int C2F(zunghr) _PARAMS((int *n, int *ilo, int *ihi, doubleC *a, int *lda, doubleC *tau, doubleC *work, int *lwork, int *info));
extern int C2F(zungl2) _PARAMS((int *m, int *n, int *k, doubleC *a, int *lda, doubleC *tau, doubleC *work, int *info));
extern int C2F(zunglq) _PARAMS((int *m, int *n, int *k, doubleC *a, int *lda, doubleC *tau, doubleC *work, int *lwork, int *info));
extern int C2F(zungql) _PARAMS((int *m, int *n, int *k, doubleC *a, int *lda, doubleC *tau, doubleC *work, int *lwork, int *info));
extern int C2F(zungqr) _PARAMS((int *m, int *n, int *k, doubleC *a, int *lda, doubleC *tau, doubleC *work, int *lwork, int *info));
extern int C2F(zungtr) _PARAMS((char *uplo, int *n, doubleC *a, int *lda, doubleC *tau, doubleC *work, int *lwork, int *info, int uplo_len));
extern int C2F(zunm2r) _PARAMS((char *side, char *trans, int *m, int *n, int *k, doubleC *a, int *lda, doubleC *tau, doubleC *c__, int *ldc, doubleC *work, int *info, int side_len, int trans_len));
extern int C2F(zunmbr) _PARAMS((char *vect, char *side, char *trans, int *m, int *n, int *k, doubleC *a, int *lda, doubleC *tau, doubleC *c__, int *ldc, doubleC *work, int *lwork, int *info, int vect_len, int side_len, int trans_len));
extern int C2F(zunml2) _PARAMS((char *side, char *trans, int *m, int *n, int *k, doubleC *a, int *lda, doubleC *tau, doubleC *c__, int *ldc, doubleC *work, int *info, int side_len, int trans_len));
extern int C2F(zunmlq) _PARAMS((char *side, char *trans, int *m, int *n, int *k, doubleC *a, int *lda, doubleC *tau, doubleC *c__, int *ldc, doubleC *work, int *lwork, int *info, int side_len, int trans_len));
extern int C2F(zunmqr) _PARAMS((char *side, char *trans, int *m, int *n, int *k, doubleC *a, int *lda, doubleC *tau, doubleC *c__, int *ldc, doubleC *work, int *lwork, int *info, int side_len, int trans_len));
extern int C2F(zunmr3) _PARAMS((char *side, char *trans, int *m, int *n, int *k, int *l, doubleC *a, int *lda, doubleC *tau, doubleC *c__, int *ldc, doubleC *work, int *info, int side_len, int trans_len));
extern int C2F(zunmrz) _PARAMS((char *side, char *trans, int *m, int *n, int *k, int *l, doubleC *a, int *lda, doubleC *tau, doubleC *c__, int *ldc, doubleC *work, int *lwork, int *info, int side_len, int trans_len));

#endif /** SCI_LAPACK_   **/
