// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
libtutorial_path="./" // get_file_path('loader.sce');
addinter(libtutorial_path+'/libtutorial.so','libtutorial');
