// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------

libtutorial_path=file('join',['.','libtutorial.dll']);
addinter(libtutorial_path,'libtutorial');
