
all:: manual

manual::
	cd generated ; make distclean; make all

index: 
	cd generated ; make index 

distclean::
	cd generated ; make distclean

clean:: 


show:
	firefox file://`pwd`/generated/manual.html

