/* config.h.  Generated by configure.  */
/* -*- Mode: C -*- */

#ifndef NSP_TCL_CONFIG_H 
#define NSP_TCL_CONFIG_H 

/* #undef mode_t */
/* #undef pid_t */
/* #undef size_t */
#define HAVE_GETCWD 1
#define HAVE_GETWD 1
/* #undef HAVE_NET_ERRNO_H */
#define HAVE_OPENDIR 1
#define HAVE_SIGNED_CHAR 1
#define HAVE_STRERROR 1
#define HAVE_STRSTR 1
/* #undef HAVE_STRTOD */
#define HAVE_STRTOL 1
#define HAVE_SYS_IOCTL_H 1
/* #undef HAVE_SYS_SELECT_H */
#define HAVE_SYS_TIME_H 1
#define HAVE_TIMEZONE_VAR 1
#define HAVE_TMPNAM 1
#define HAVE_TM_GMTOFF 1
/* #undef HAVE_TM_TZADJ */
/* #undef HAVE_TZNAME */
/* #undef HAVE_UNAME */
#define HAVE_UNISTD_H 1
/* #undef HAVE_VFORK */
/* #undef HAVE_WAIT3 */
#define HAVE_WAITPID 1
#define NEED_MATHERR 1
/* #undef NO_DIRENT_H */
/* #undef NO_DLFCN_H */
/* #undef NO_ERRNO_H */
/* #undef NO_FD_SET */
/* #undef NO_FLOAT_H */
/* #undef NO_GETWD */
/* #undef NO_LIMITS_H */
/* #undef NO_STDLIB_H */
/* #undef NO_STRERROR */
/* #undef NO_STRING_H */
/* #undef NO_SYS_WAIT_H */
/* #undef NO_UNAME */
/* #undef NO_UNION_WAIT */
/* #undef NO_VALUES_H */
/* #undef NO_WAIT3 */
/* #undef TM_IN_SYS_TIME_H */
/* #undef USEGETWD */
/* #undef USE_DELTA_FOR_TZ */
/* #undef USE_DIRENT2_H */
/* #undef USE_FIONBIO */
/* #undef USE_SGTTY */
/* #undef USE_TERMIO */
#define USE_TERMIOS 1

#endif
