# Copyright INRIA

FFLAGS = $(FC_OPTIONS)

LIBS=-Wl,--whole-archive libs/nsp.a  \
	libs/zcalelm.a libs/zblas.a libs/graphics.a \
	libs/gtksci.a libs/menusX.a libs/rand.a libs/dcd.a  \
	libs/integ.a libs/approx.a libs/lapack.a \
	-Wl,--no-whole-archive

bin/scilex: scilex-lib 
	@$(RM) $@;
	@echo "linking"; 
	$(FC)  $(FFLAGS) -o $@ src/interp/lsci.o $(FC_LDFLAGS) \
	$(LIBS) $(TCLTK_LIBS) $(XLIBS) $(TERMCAPLIB);

