# Copyright Enpc 

FFLAGS = $(FC_OPTIONS)

# to load all the static libraries 
# -Wl,all_load 

LIBS=  $(NSPLIBS) 

bin/scilex: scilex-lib 
	@$(RM) $@;
	@echo "linking"; 
	$(CC)  $(FFLAGS) -o $@ src/interp/lsci.o \
		$(NSPLIBS) $(EXTERNLIBS) $(FC_LDFLAGS) -lg2c ;





