# Copyright ENPC 

FFLAGS = $(FC_OPTIONS)

LIBS=-Wl,--whole-archive $(NSPLIBS) -Wl,--no-whole-archive 

bin/scilex: scilex-lib 
	@$(RM) $@;
	@echo "linking"; 
	@$(FC)  $(FFLAGS) -o $@ src/interp/lsci.o \
		$(LIBS) $(EXTERNLIBS) $(FC_LDFLAGS) $(WIN32LIBS)




