if ~new_graphics() then switch_graphics();end;xclear();
xclear();
exec('interpolation_code.sci');xset('wshow');xclick()
xclear()
exec('icm_code.sci');xset('wshow');xclick()
xclear()
exec('seuil_code.sci');xset('wshow');xclick()
xclear()
exec('efficacite_code.sci');xset('wshow');xclick()
xclear()
exec('evolution_ratio_code.sci');xset('wshow');xclick()
xclear()
exec('diag_effets.sci');xset('wshow');xclick()
xclear()
exec('pareto_code.sci');xset('wshow');xclick()
