/* do not edit : generated by ilib_ */
#include "nsp/machine.h"
#include "nsp/interf.h"


extern function int_optim;
extern function int_n1qn1d_test;

static OpWrapTab liboptim_func[] = {
  {"optim", int_optim,NULL},
  {"optim_test", int_n1qn1d_test,NULL},
  {(char *) 0, NULL, NULL},
};
int liboptim_Interf (int i, Stack stack, int rhs, int opt, int lhs)
{
  if ( liboptim_func[i].wrapper == NULL)
     return (*(liboptim_func[i].fonc)) (stack, rhs, opt, lhs);
  else 
     return (*(liboptim_func[i].wrapper)) (stack, rhs, opt, lhs,liboptim_func[i].fonc);
}
void liboptim_Interf_Info (int i, char **fname, function (**f))
{
 *fname = liboptim_func[i].name;
 *f = liboptim_func[i].fonc;
}
