// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------

libminpack_path=file('join',['.','libminpack.so']);
addinter(libminpack_path,'libminpack');
