#/* -*- Mode: Makefile -*- */

all	::
	@echo "processing *.sci files" 
	@$(SCIDIR)/bin/scilex -nw -dir ./

clean	::
	@echo "Cleaning"
	@$(RM) *.bin

silent-clean ::
	@$(RM) *.bin

distclean:: clean 

silent-distclean :: silent-clean
