#/* -*- Mode: Makefile -*- */

all	::
	@echo "processing *.sci files" 
	@$(SCIDIR)/bin/scilex -nw -ns -dir ./

clean	::
	@echo "Cleaning"
	@$(RM) *.bin

silent-clean ::
	@$(RM) *.bin

distclean:: clean 

silent-distclean :: silent-clean

PP=$(patsubst %.sci,%_pp.sci,$(wildcard *.sci))

pp : $(PP) 

%_pp.sci : %.sci
	@echo "pretty print $*.sci"
	@$(SCIDIR)/bin/scilex -nw -ns -e "pretty_printer('$*.sci');quit"
	@diff -riw $*.sci $*_pp.sci && ([ $$? -eq 0 ] && echo -n "") || echo -n "" 

clean	::
	@$(RM) $(PP)


