/* do not edit : generated by ilib_ */
#include "nsp/machine.h"
#include "nsp/interf.h"


extern function int_ex1c;
extern function int_ex2c;
extern function int_ex_3c_1;
extern function int_ex_4c_1;
extern function int_ex_4c_2;
extern function int_ex_4c_3;
extern function int_ex_4c_4;
extern function int_ex_5c_1;
extern function int_ex_5c_2;
extern function int_ex_6c_1;
extern function int_ex_7c_1;
extern function int_ex_18c_1;

static OpWrapTab libtour_func[] = {
  {"ex1c", int_ex1c,NULL},
  {"ex2c", int_ex2c,NULL},
  {"ex3c_1", int_ex_3c_1,NULL},
  {"ex4c_1", int_ex_4c_1,NULL},
  {"ex4c_2", int_ex_4c_2,NULL},
  {"ex4c_3", int_ex_4c_3,NULL},
  {"ex4c_4", int_ex_4c_4,NULL},
  {"ex5c_1", int_ex_5c_1,NULL},
  {"ex5c_2", int_ex_5c_2,NULL},
  {"ex6c_1", int_ex_6c_1,NULL},
  {"ex7c_1", int_ex_7c_1,NULL},
  {"ex18c_1", int_ex_18c_1,NULL},
  {(char *) 0, NULL, NULL},
};
int libtour_Interf (int i, Stack stack, int rhs, int opt, int lhs)
{
  if ( libtour_func[i].wrapper == NULL)
     return (*(libtour_func[i].fonc)) (stack, rhs, opt, lhs);
  else 
     return (*(libtour_func[i].wrapper)) (stack, rhs, opt, lhs,libtour_func[i].fonc);
}
void libtour_Interf_Info (int i, char **fname, function (**f))
{
 *fname = libtour_func[i].name;
 *f = libtour_func[i].fonc;
}
