/* do not edit : generated by ilib_ */
#include "nsp/machine.h"
#include "nsp/interf.h"


extern function int_first;
extern function int_second;

static OpWrapTab libtutorial_func[] = {
  {"first", int_first,NULL},
  {"second", int_second,NULL},
  {(char *) 0, NULL, NULL},
};
int libtutorial_Interf (int i, Stack stack, int rhs, int opt, int lhs)
{
  if ( libtutorial_func[i].wrapper == NULL)
     return (*(libtutorial_func[i].fonc)) (stack, rhs, opt, lhs);
  else 
     return (*(libtutorial_func[i].wrapper)) (stack, rhs, opt, lhs,libtutorial_func[i].fonc);
}
void libtutorial_Interf_Info (int i, char **fname, function (**f))
{
 *fname = libtutorial_func[i].name;
 *f = libtutorial_func[i].fonc;
}
