// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
libtour_path="./" // get_file_path('loader.sce');
addinter(libtour_path+'/libtour.so','libtour');
